name: Check code with eslint

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint
        env:
          CI: true
          BASE: ${{ github.base_ref }}
          HEAD: ${{ github.head_ref }}
